/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controllers.InstituicaoController;
import DTOs.BolsaDTO;
import Entities.Instituicao;
import Repositories.InstituicaoRepository;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.BorderFactory;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author Blackmage
 */
public class TelaGerenciamentoBolsas extends javax.swing.JFrame {
    
    private static Instituicao instituicao;

    /**
     * Creates new form TelaGerenciamentoBolsas
     * @param instituicao
     */
    public TelaGerenciamentoBolsas(Instituicao instituicao) {
        initComponents();
        configurarTabela();
        fundoPopup.setVisible(false);
        this.instituicao = instituicao;
    }
    
    public TelaGerenciamentoBolsas(){
        initComponents();
        configurarTabela();
        fundoPopup.setVisible(false);
    }
    
    private void configurarTabela() {
        DefaultTableModel model = (DefaultTableModel) tblBolsas.getModel();

        // Pega a última coluna da tabela (a "Excluir")
        TableColumn column = tblBolsas.getColumnModel().getColumn(tblBolsas.getColumnCount() - 1);
    
        // Configura a coluna "Excluir" para exibir botões
        column.setCellRenderer(new ButtonRenderer());
        column.setCellEditor(new ButtonEditor(new JCheckBox()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundoPopup = new javax.swing.JPanel();
        panelPopup = new RoundedPanel(100, Color.WHITE);
        btnFecharPopup = new javax.swing.JButton();
        txtTipoBolsa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNomeCurso = new javax.swing.JTextField();
        txtPrecoBolsa = new javax.swing.JTextField();
        txtDescricaoBolsa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSalvarBolsa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnPesquisa = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBolsas = new javax.swing.JTable();
        labelInst = new javax.swing.JLabel();
        btnShow = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1160, 720));
        setPreferredSize(new java.awt.Dimension(1160, 720));
        getContentPane().setLayout(null);

        fundoPopup.setBackground(new java.awt.Color(80, 80, 80, 130));
        fundoPopup.setLayout(new java.awt.GridBagLayout());

        panelPopup.setBackground(new java.awt.Color(80, 80, 80, 0));
        panelPopup.setPreferredSize(new java.awt.Dimension(800, 400));
        panelPopup.setLayout(null);

        btnFecharPopup.setText("Concluir");
        btnFecharPopup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFecharPopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharPopupActionPerformed(evt);
            }
        });
        panelPopup.add(btnFecharPopup);
        btnFecharPopup.setBounds(590, 320, 150, 40);

        txtTipoBolsa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtTipoBolsa.setForeground(java.awt.Color.gray);
        txtTipoBolsa.setText("Digite o tipo de bolsa...");
        txtTipoBolsa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTipoBolsaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTipoBolsaFocusLost(evt);
            }
        });
        panelPopup.add(txtTipoBolsa);
        txtTipoBolsa.setBounds(470, 210, 250, 40);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(75, 109, 190));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Adicionar Bolsa");
        panelPopup.add(jLabel1);
        jLabel1.setBounds(250, 30, 310, 50);

        txtNomeCurso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNomeCurso.setForeground(java.awt.Color.gray);
        txtNomeCurso.setText("Digite o nome do curso...");
        txtNomeCurso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeCursoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeCursoFocusLost(evt);
            }
        });
        panelPopup.add(txtNomeCurso);
        txtNomeCurso.setBounds(100, 130, 250, 40);

        txtPrecoBolsa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPrecoBolsa.setForeground(java.awt.Color.gray);
        txtPrecoBolsa.setText("Digite o preço da bolsa...");
        txtPrecoBolsa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrecoBolsaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecoBolsaFocusLost(evt);
            }
        });
        panelPopup.add(txtPrecoBolsa);
        txtPrecoBolsa.setBounds(100, 210, 250, 40);

        txtDescricaoBolsa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDescricaoBolsa.setForeground(java.awt.Color.gray);
        txtDescricaoBolsa.setText("Dê uma descrição para a bolsa...");
        txtDescricaoBolsa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescricaoBolsaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescricaoBolsaFocusLost(evt);
            }
        });
        panelPopup.add(txtDescricaoBolsa);
        txtDescricaoBolsa.setBounds(470, 130, 250, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Descrição da bolsa");
        panelPopup.add(jLabel2);
        jLabel2.setBounds(470, 110, 130, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Nome do curso");
        panelPopup.add(jLabel3);
        jLabel3.setBounds(100, 110, 130, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Preço da bolsa");
        panelPopup.add(jLabel4);
        jLabel4.setBounds(100, 190, 130, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Tipo de bolsa");
        panelPopup.add(jLabel5);
        jLabel5.setBounds(470, 190, 130, 20);

        btnSalvarBolsa.setText("Salvar");
        btnSalvarBolsa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvarBolsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarBolsaActionPerformed(evt);
            }
        });
        panelPopup.add(btnSalvarBolsa);
        btnSalvarBolsa.setBounds(340, 280, 150, 40);

        fundoPopup.add(panelPopup, new java.awt.GridBagConstraints());

        getContentPane().add(fundoPopup);
        fundoPopup.setBounds(0, 0, 1160, 720);

        jPanel1.setBackground(new java.awt.Color(75, 109, 190));
        jPanel1.setLayout(null);

        btnPesquisa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tool_16205471.png"))); // NOI18N
        btnPesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisa);
        btnPesquisa.setBounds(320, 110, 40, 40);

        txtPesquisa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPesquisa.setForeground(java.awt.Color.gray);
        txtPesquisa.setText("Clique para pesquisar");
        txtPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesquisaFocusLost(evt);
            }
        });
        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(txtPesquisa);
        txtPesquisa.setBounds(80, 110, 230, 40);

        tblBolsas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblBolsas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome do Curso", "Descrição da Bolsa", "Tipo de Bolsa", "Preço", "Excluir"
            }
        ));
        jScrollPane1.setViewportView(tblBolsas);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 190, 1000, 340);

        labelInst.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        labelInst.setForeground(new java.awt.Color(255, 255, 255));
        labelInst.setText("Bolsas");
        labelInst.setToolTipText("");
        labelInst.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(labelInst);
        labelInst.setBounds(80, 60, 240, 40);

        btnShow.setText("Atualizar Bolsas");
        btnShow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        jPanel1.add(btnShow);
        btnShow.setBounds(720, 110, 170, 40);

        btnAdd.setText("Adicionar Bolsa");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd);
        btnAdd.setBounds(910, 110, 170, 40);

        btnPerfil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPerfil.setText("Página de Perfil");
        btnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(btnPerfil);
        btnPerfil.setBounds(840, 580, 240, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1160, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        InstituicaoRepository instituicaoRepository = new InstituicaoRepository();
        instituicaoRepository.getAllBolsas(tblBolsas, instituicao);
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        fundoPopup.setVisible(true);
        fundoPopup.addMouseListener(new MouseAdapter() {});
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaFocusGained
        txtPesquisa.setText("");
    }//GEN-LAST:event_txtPesquisaFocusGained

    private void txtPesquisaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaFocusLost
        txtPesquisa.setText("Clique para pesquisar");
    }//GEN-LAST:event_txtPesquisaFocusLost

    private void btnFecharPopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharPopupActionPerformed
        // TODO add your handling code here:
        fundoPopup.setVisible(false);
    }//GEN-LAST:event_btnFecharPopupActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        TelaPerfilInstituicao telaPerfilInstituicao =  new TelaPerfilInstituicao();
        telaPerfilInstituicao.pack();
        dispose();
        telaPerfilInstituicao.setVisible(true);
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void txtNomeCursoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeCursoFocusGained
        //txtNomeCurso.setText("");
    }//GEN-LAST:event_txtNomeCursoFocusGained

    private void txtNomeCursoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeCursoFocusLost
        //txtNomeCurso.setText("Digite o nome do curso...");
    }//GEN-LAST:event_txtNomeCursoFocusLost

    private void txtPrecoBolsaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecoBolsaFocusGained
        //txtPrecoBolsa.setText("");
    }//GEN-LAST:event_txtPrecoBolsaFocusGained

    private void txtPrecoBolsaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecoBolsaFocusLost
        //txtPrecoBolsa.setText("Digite o preço da bolsa...");
    }//GEN-LAST:event_txtPrecoBolsaFocusLost

    private void txtDescricaoBolsaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescricaoBolsaFocusGained
        //txtDescricaoBolsa.setText("");
    }//GEN-LAST:event_txtDescricaoBolsaFocusGained

    private void txtDescricaoBolsaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescricaoBolsaFocusLost
        //txtDescricaoBolsa.setText("Dê uma descrição para a bolsa...");
    }//GEN-LAST:event_txtDescricaoBolsaFocusLost

    private void txtTipoBolsaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoBolsaFocusGained
        //txtTipoBolsa.setText("");
    }//GEN-LAST:event_txtTipoBolsaFocusGained

    private void txtTipoBolsaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoBolsaFocusLost
        //txtTipoBolsa.setText("Digite o tipo de bolsa...");
    }//GEN-LAST:event_txtTipoBolsaFocusLost

    private void btnSalvarBolsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarBolsaActionPerformed
        BolsaDTO bolsaDTO = new BolsaDTO();
        InstituicaoController instituicaoController = new InstituicaoController();
        
        bolsaDTO.setNome(txtNomeCurso.getText());
        bolsaDTO.setDescricaoBolsa(txtDescricaoBolsa.getText());
        bolsaDTO.setPrecoBolsa(Double.parseDouble(txtPrecoBolsa.getText()));
        bolsaDTO.setTipoBolsa(txtTipoBolsa.getText());
        bolsaDTO.setIdInstituicao(instituicao.getIdIntituicao());
        
        if (instituicaoController.addBolsas(bolsaDTO)) {
            JOptionPane.showMessageDialog(null, "Bolsa cadastrada com sucesso!!");
        }
    }//GEN-LAST:event_btnSalvarBolsaActionPerformed

    private void txtNomeCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCursoActionPerformed
    
    
    
    // Classe para renderizar o botão na célula 
    class ButtonRenderer extends JButton implements TableCellRenderer {
        public ButtonRenderer() {
            setText("Excluir");
            setBackground(Color.WHITE);
            setForeground(Color.BLACK);
            setFont(new Font("Arial", Font.BOLD, 12));
            setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));
            setFocusPainted(false);
            setPreferredSize(new Dimension(80, 30));
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            return this;
        }
    }

    // Classe para editar a célula (definir o que acontece quando o botão é clicado)
    class ButtonEditor extends DefaultCellEditor {
        private JButton button;
        private int row;  // A linha do botão clicado

        public ButtonEditor(JCheckBox checkBox) {
            super(checkBox);
            button = new JButton();
            button.setOpaque(true);
            button.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    fireEditingStopped();  // Para parar a edição da célula
                    DefaultTableModel model = (DefaultTableModel) tblBolsas.getModel();
                    model.removeRow(row);  // Remove a linha da tabela
                }
            });
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            this.row = row;
            button.setText("Excluir");
            return button;
        }

        @Override
        public Object getCellEditorValue() {
            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciamentoBolsas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciamentoBolsas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciamentoBolsas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciamentoBolsas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaGerenciamentoBolsas telaGerenciamentoBolsas = new TelaGerenciamentoBolsas(instituicao);
                telaGerenciamentoBolsas.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnFecharPopup;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnSalvarBolsa;
    private javax.swing.JButton btnShow;
    private javax.swing.JPanel fundoPopup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelInst;
    private javax.swing.JPanel panelPopup;
    private javax.swing.JTable tblBolsas;
    private javax.swing.JTextField txtDescricaoBolsa;
    private javax.swing.JTextField txtNomeCurso;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtPrecoBolsa;
    private javax.swing.JTextField txtTipoBolsa;
    // End of variables declaration//GEN-END:variables

    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }

}
