/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Repositories.AdminRepository;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Blackmage
 */
public class TelaGerenciamentoInst extends javax.swing.JFrame {

    /**
     * Creates new form TelaGerenciamentoInst
     */
    public TelaGerenciamentoInst() {
        initComponents();
        fundoPopup.setVisible(false);
        jPanel1.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundoPopup = new javax.swing.JPanel();
        panelPopup = new RoundedPanel(100, Color.WHITE);
        btnFecharPopup = new javax.swing.JButton();
        txtTipoBolsa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNomeCurso = new javax.swing.JTextField();
        txtPrecoBolsa = new javax.swing.JTextField();
        txtDescricaoBolsa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSalvarInst = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnPesquisa = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInst = new javax.swing.JTable();
        labelInst = new javax.swing.JLabel();
        btnShow = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1160, 720));
        setPreferredSize(new java.awt.Dimension(1160, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1160, 720));
        getContentPane().setLayout(null);

        fundoPopup.setBackground(new java.awt.Color(80, 80, 80, 130));
        fundoPopup.setLayout(new java.awt.GridBagLayout());

        panelPopup.setBackground(new java.awt.Color(80, 80, 80, 0));
        panelPopup.setPreferredSize(new java.awt.Dimension(800, 400));
        panelPopup.setLayout(null);

        btnFecharPopup.setText("Concluir");
        btnFecharPopup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFecharPopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharPopupActionPerformed(evt);
            }
        });
        panelPopup.add(btnFecharPopup);
        btnFecharPopup.setBounds(600, 320, 120, 40);

        txtTipoBolsa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelPopup.add(txtTipoBolsa);
        txtTipoBolsa.setBounds(470, 210, 250, 40);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(75, 109, 190));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Adicionar Instituição");
        panelPopup.add(jLabel1);
        jLabel1.setBounds(230, 30, 350, 50);

        txtNomeCurso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelPopup.add(txtNomeCurso);
        txtNomeCurso.setBounds(100, 130, 250, 40);

        txtPrecoBolsa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelPopup.add(txtPrecoBolsa);
        txtPrecoBolsa.setBounds(100, 210, 250, 40);

        txtDescricaoBolsa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelPopup.add(txtDescricaoBolsa);
        txtDescricaoBolsa.setBounds(470, 130, 250, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Descrição da bolsa");
        panelPopup.add(jLabel2);
        jLabel2.setBounds(470, 110, 130, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Nome do curso");
        panelPopup.add(jLabel3);
        jLabel3.setBounds(100, 110, 130, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Preço da bolsa");
        panelPopup.add(jLabel4);
        jLabel4.setBounds(100, 190, 130, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Tipo de bolsa");
        panelPopup.add(jLabel5);
        jLabel5.setBounds(470, 190, 130, 20);

        btnSalvarInst.setText("Salvar");
        btnSalvarInst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvarInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarInstActionPerformed(evt);
            }
        });
        panelPopup.add(btnSalvarInst);
        btnSalvarInst.setBounds(330, 290, 170, 40);

        fundoPopup.add(panelPopup, new java.awt.GridBagConstraints());

        getContentPane().add(fundoPopup);
        fundoPopup.setBounds(0, 0, 1160, 720);

        jPanel1.setBackground(new java.awt.Color(75, 109, 190));
        jPanel1.setMinimumSize(new java.awt.Dimension(1160, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1160, 720));
        jPanel1.setLayout(null);

        btnPesquisa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tool_16205471.png"))); // NOI18N
        btnPesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisa);
        btnPesquisa.setBounds(320, 110, 40, 40);

        txtPesquisa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPesquisa.setForeground(java.awt.Color.gray);
        txtPesquisa.setText("Clique para pesquisar");
        txtPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesquisaFocusLost(evt);
            }
        });
        jPanel1.add(txtPesquisa);
        txtPesquisa.setBounds(80, 110, 230, 40);

        tblInst.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblInst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "E-MAIL", "SIGLA", "CNPJ", "CEP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInst);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 190, 1000, 400);

        labelInst.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        labelInst.setForeground(new java.awt.Color(255, 255, 255));
        labelInst.setText("Instituições");
        labelInst.setToolTipText("");
        labelInst.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(labelInst);
        labelInst.setBounds(80, 60, 240, 40);

        btnShow.setText("Atualizar Lista");
        btnShow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        jPanel1.add(btnShow);
        btnShow.setBounds(450, 110, 150, 40);

        btnAdicionar.setText("Adicionar Instituição");
        btnAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdicionar);
        btnAdicionar.setBounds(610, 110, 150, 40);

        btnExcluir.setText("Excluir");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir);
        btnExcluir.setBounds(930, 110, 150, 40);

        btnEditar.setText("Editar");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar);
        btnEditar.setBounds(770, 110, 150, 40);

        btnVoltar.setText("Concluir");
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar);
        btnVoltar.setBounds(830, 610, 250, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1160, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        AdminRepository adminRepository = new AdminRepository();
        adminRepository.getAllInstituicoes(tblInst);
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        fundoPopup.setVisible(true);
        fundoPopup.addMouseListener(new MouseAdapter() {});
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tblInst.getSelectedRow();
        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(rootPane, "Selecione a linha a ser excluída.");
        } else {
            DefaultTableModel tabelaInst = (DefaultTableModel) tblInst.getModel();
            tabelaInst.removeRow(linhaSelecionada);
            JOptionPane.showMessageDialog(this, "Instituição excluída com sucesso.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaFocusGained
        if(txtPesquisa.getText().equals("Clique para pesquisar")){
            txtPesquisa.setText("");
            txtPesquisa.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtPesquisaFocusGained

    private void txtPesquisaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaFocusLost
        if(txtPesquisa.getText().isEmpty()){
            txtPesquisa.setText("Clique para pesquisar");
            txtPesquisa.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtPesquisaFocusLost

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int linhaSelecionada = tblInst.getSelectedRow();
        int colunaSelecionada = tblInst.getSelectedColumn();
        
        if(linhaSelecionada == -1 || colunaSelecionada == -1){
            JOptionPane.showMessageDialog(rootPane, "Selecione a célula a ser editada.");
        } else {
            DefaultTableModel tabelaInst = (DefaultTableModel) tblInst.getModel();
            
            Object valorAtual = tabelaInst.getValueAt(linhaSelecionada, colunaSelecionada);
            
            String novoValor = JOptionPane.showInputDialog(this, 
                "Digite o novo valor para a célula selecionada:", valorAtual);
            
            if (novoValor != null && !novoValor.trim().isEmpty()) {
                // Altera o valor na célula selecionada
                tabelaInst.setValueAt(novoValor, linhaSelecionada, colunaSelecionada);
                JOptionPane.showMessageDialog(this, "Valor alterado com sucesso.");
            } else {
                JOptionPane.showMessageDialog(this, "Valor inválido ou vazio.");
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnFecharPopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharPopupActionPerformed
        // TODO add your handling code here:
        fundoPopup.setVisible(false);
    }//GEN-LAST:event_btnFecharPopupActionPerformed

    private void btnSalvarInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarInstActionPerformed
        
    }//GEN-LAST:event_btnSalvarInstActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaDashboard telaDashboard = new TelaDashboard();
        this.dispose();
        telaDashboard.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciamentoInst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciamentoInst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciamentoInst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciamentoInst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaGerenciamentoInst tela = new TelaGerenciamentoInst();
            tela.setVisible(true);

            tela.txtPesquisa.addFocusListener(new java.awt.event.FocusListener() {
                public void focusGained(java.awt.event.FocusEvent evt) {
                    // Quando o campo ganha o foco, remove o texto padrão
                    if (tela.txtPesquisa.getText().equals("Clique para pesquisar")) {
                        tela.txtPesquisa.setText("");
                        tela.txtPesquisa.setForeground(java.awt.Color.BLACK); // Texto visível
                    }
                }

                public void focusLost(java.awt.event.FocusEvent evt) {
                    // Quando o campo perde o foco, se o texto estiver vazio, restaura o texto inicial
                    if (tela.txtPesquisa.getText().isEmpty()) {
                        tela.txtPesquisa.setText("Clique para pesquisar");
                        tela.txtPesquisa.setForeground(java.awt.Color.GRAY); // Texto cinza
                    }
                }
            });
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFecharPopup;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnSalvarInst;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel fundoPopup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelInst;
    private javax.swing.JPanel panelPopup;
    private javax.swing.JTable tblInst;
    private javax.swing.JTextField txtDescricaoBolsa;
    private javax.swing.JTextField txtNomeCurso;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtPrecoBolsa;
    private javax.swing.JTextField txtTipoBolsa;
    // End of variables declaration//GEN-END:variables

    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }

}
