/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DTOs.BolsaDTO;
import Entities.Aluno;
import Entities.Bolsas;
import Services.AlunoService;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author Blackmage
 */
public class TelaConsultaBolsas extends javax.swing.JFrame {
    
    private static Aluno aluno;

    /**
     * Creates new form TelaConsultaBolsas
     * @param aluno
     */
    public TelaConsultaBolsas(Aluno aluno) {
        initComponents();
        configurarTabela();
        this.aluno = aluno;
        fundoPopup.setVisible(false);
    }
    
    public TelaConsultaBolsas(){
        initComponents();
        configurarTabela();
        fundoPopup.setVisible(false);
    }
    
    private void configurarTabela() {
        DefaultTableModel model = (DefaultTableModel) tblConsulta.getModel();

        TableColumn column = tblConsulta.getColumnModel().getColumn(tblConsulta.getColumnCount() - 1);
    
        column.setCellRenderer(new ButtonRenderer());
        column.setCellEditor(new ButtonEditor(new JCheckBox()));
        
        tblConsulta.addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent e) {
            int row = tblConsulta.rowAtPoint(e.getPoint());
            int column = tblConsulta.columnAtPoint(e.getPoint());
            System.out.println("Célula pressionada: " + row + ", " + column);

            if (column == tblConsulta.getColumnCount() - 1) {
                //Aqui ocorre a ação q quiser do botão de detalhes
                tblConsulta.editCellAt(row, column);
                fundoPopup.setVisible(true);
                fundoPopup.addMouseListener(new MouseAdapter() {});
            }
        }
    });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fundoPopup = new javax.swing.JPanel();
        panelPopup = new RoundedPanel(100, Color.WHITE);
        btnFecharPopup = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtNomeCurso = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescricaoBolsa = new javax.swing.JTextArea();
        txtEmail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsulta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1160, 720));
        setPreferredSize(new java.awt.Dimension(1160, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1160, 720));
        getContentPane().setLayout(null);

        fundoPopup.setBackground(new java.awt.Color(80, 80, 80, 130));
        fundoPopup.setMinimumSize(new java.awt.Dimension(1160, 720));
        fundoPopup.setPreferredSize(new java.awt.Dimension(1160, 720));
        fundoPopup.setLayout(new java.awt.GridBagLayout());

        panelPopup.setBackground(new java.awt.Color(80, 80, 80, 0));
        panelPopup.setMinimumSize(new java.awt.Dimension(800, 420));
        panelPopup.setLayout(null);

        btnFecharPopup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close-icon.png"))); // NOI18N
        btnFecharPopup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFecharPopup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharPopupActionPerformed(evt);
            }
        });
        panelPopup.add(btnFecharPopup);
        btnFecharPopup.setBounds(690, 20, 40, 40);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(75, 109, 190));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Detalhes da Bolsa");
        panelPopup.add(jLabel12);
        jLabel12.setBounds(250, 20, 310, 50);

        txtNomeCurso.setEditable(false);
        txtNomeCurso.setBackground(java.awt.Color.white);
        txtNomeCurso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNomeCurso.setBorder(null);
        txtNomeCurso.setFocusable(false);
        txtNomeCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCursoActionPerformed(evt);
            }
        });
        panelPopup.add(txtNomeCurso);
        txtNomeCurso.setBounds(220, 90, 240, 40);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Descrição da bolsa:");
        panelPopup.add(jLabel13);
        jLabel13.setBounds(50, 250, 160, 20);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Email de contato:");
        panelPopup.add(jLabel14);
        jLabel14.setBounds(90, 200, 120, 20);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtDescricaoBolsa.setEditable(false);
        txtDescricaoBolsa.setBackground(new java.awt.Color(255, 255, 255));
        txtDescricaoBolsa.setColumns(20);
        txtDescricaoBolsa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDescricaoBolsa.setRows(5);
        txtDescricaoBolsa.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        txtDescricaoBolsa.setFocusable(false);
        jScrollPane2.setViewportView(txtDescricaoBolsa);

        panelPopup.add(jScrollPane2);
        jScrollPane2.setBounds(220, 250, 430, 130);

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmail.setBorder(null);
        txtEmail.setFocusable(false);
        panelPopup.add(txtEmail);
        txtEmail.setBounds(220, 190, 240, 40);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Nome do curso:");
        panelPopup.add(jLabel15);
        jLabel15.setBounds(90, 100, 120, 20);

        txtTelefone.setEditable(false);
        txtTelefone.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTelefone.setBorder(null);
        txtTelefone.setFocusable(false);
        panelPopup.add(txtTelefone);
        txtTelefone.setBounds(220, 140, 240, 40);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Telefone de contato:");
        panelPopup.add(jLabel16);
        jLabel16.setBounds(60, 150, 150, 20);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/faculdade-icon.png"))); // NOI18N
        panelPopup.add(jLabel17);
        jLabel17.setBounds(490, 80, 140, 140);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 800;
        gridBagConstraints.ipady = 420;
        gridBagConstraints.weightx = 800.0;
        gridBagConstraints.weighty = 420.0;
        gridBagConstraints.insets = new java.awt.Insets(80, 0, 0, 0);
        fundoPopup.add(panelPopup, gridBagConstraints);

        getContentPane().add(fundoPopup);
        fundoPopup.setBounds(0, 0, 1160, 720);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(1160, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1160, 720));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(75, 109, 190));
        jPanel2.setLayout(null);

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 102, 255));
        jButton2.setText("Buscar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(500, 190, 200, 50);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(910, 100, 120, 40);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(320, 100, 170, 40);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(510, 100, 170, 40);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField4);
        jTextField4.setBounds(130, 100, 170, 40);

        jSlider1.setMajorTickSpacing(20000);
        jSlider1.setMaximum(1000000);
        jSlider1.setMinimum(5000);
        jSlider1.setMinorTickSpacing(5000);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jSlider1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSlider1MouseDragged(evt);
            }
        });
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSlider1MouseClicked(evt);
            }
        });
        jPanel2.add(jSlider1);
        jSlider1.setBounds(700, 110, 200, 20);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Curso");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(130, 80, 40, 17);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome da Instituição");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(320, 80, 140, 17);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cidade");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(510, 80, 50, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Valor máximo");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(710, 80, 90, 17);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 1160, 260);

        jPanel3.setBackground(new java.awt.Color(255, 203, 105));
        jPanel3.setLayout(null);

        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(75, 109, 190));
        jButton3.setText("Teste Vocacional");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(0, 270, 220, 50);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("AINDA NÃO SABE QUAL");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 30, 160, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CURSO ESCOLHER?");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(40, 60, 150, 17);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FAÇA NOSSO NOVO");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(40, 110, 150, 17);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TESTE VOCACIONAL E");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(30, 140, 160, 17);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DESCUBRA SUAS");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(50, 170, 115, 17);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("HABILIDADES E");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(50, 200, 101, 17);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NECESSIDADES!!!");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(40, 230, 130, 17);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(920, 260, 220, 320);

        jButton1.setBackground(new java.awt.Color(75, 109, 190));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Perfil");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(920, 590, 220, 50);

        tblConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome do curso", "Faculdade", "Preço", "Tipo de bolsa", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblConsulta.setRowHeight(25);
        jScrollPane1.setViewportView(tblConsulta);
        if (tblConsulta.getColumnModel().getColumnCount() > 0) {
            tblConsulta.getColumnModel().getColumn(4).setMinWidth(80);
            tblConsulta.getColumnModel().getColumn(4).setMaxWidth(80);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 290, 830, 350);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1160, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nomeDoCurso = jTextField4.getText().toLowerCase();
        String nomeDaInstituicao = jTextField2.getText().toLowerCase();
        String cidade = jTextField3.getText().toLowerCase();
        Double preco = Double.valueOf(jTextField1.getText().replace(',', '.'));
        
        BolsaDTO bolsaDTO = new BolsaDTO();
        bolsaDTO.setNome(nomeDoCurso);
        bolsaDTO.setInstituicao(nomeDaInstituicao);
        bolsaDTO.setCidade(cidade);
        bolsaDTO.setPrecoBolsa(preco);
        

        AlunoService alunoService = new AlunoService();
        List<Bolsas> bolsas = alunoService.findBolsas(bolsaDTO);
        
        DefaultTableModel model = (DefaultTableModel) tblConsulta.getModel();
        
        model.setRowCount(0);
        for (Bolsas bolsa : bolsas) {
                model.addRow(new Object[]{
                bolsa.getNome(),           // Nome da bolsa
                bolsa.getInstituicao(),    // Nome da instituição
                bolsa.getPrecoBolsa(),      // Preço da bolsa
                bolsa.getTipoBolsa()
            });
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println("Aluno: " + aluno.getEmail() + " " + aluno.getNomeAluno() + " " + aluno.getType());
        TelaPerfilAluno telaPerfilAluno = new TelaPerfilAluno();
        telaPerfilAluno.pack();
        dispose();
        telaPerfilAluno.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TelaTesteVocacional telaTesteVocacional = new TelaTesteVocacional();
        this.dispose();
        telaTesteVocacional.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jSlider1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseClicked
        int number3;
        
        number3 = jSlider1.getValue();
        jTextField1.setText(Integer.toString(number3));
    }//GEN-LAST:event_jSlider1MouseClicked

    private void jSlider1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseDragged
        int number2;
        
        number2 = jSlider1.getValue();
        jTextField1.setText(Integer.toString(number2));
    }//GEN-LAST:event_jSlider1MouseDragged

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        int value = jSlider1.getValue();
        
        double price = value / 100.0;
        jTextField1.setText(String.format("%.2f", price));
    }//GEN-LAST:event_jSlider1StateChanged

    private void btnFecharPopupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharPopupActionPerformed
        // TODO add your handling code here:
        fundoPopup.setVisible(false);
    }//GEN-LAST:event_btnFecharPopupActionPerformed

    private void txtNomeCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCursoActionPerformed

    public class ButtonRenderer extends JButton implements TableCellRenderer {

        public ButtonRenderer() {
            setOpaque(true);
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
                boolean hasFocus, int row, int column) {

            // Carregando a imagem
            ImageIcon icon = new ImageIcon(getClass().getResource("/detalhes-icon.png"));

            // Redimensionando a imagem para 20x20
            Image img = icon.getImage().getScaledInstance(10, 10, Image.SCALE_SMOOTH);
            icon = new ImageIcon(img);

            setIcon(icon);  // Definindo a imagem como ícone do botão

            // Alterando o fundo do botão se a célula estiver selecionada
            if (isSelected) {
                setBackground(Color.LIGHT_GRAY);
            } else {
                setBackground(Color.WHITE);
            }

            return this;
        }
    }
    
    public class ButtonEditor extends DefaultCellEditor {
        private JButton button;
        private boolean isPushed;

        public ButtonEditor(JCheckBox checkBox) {
            super(checkBox);
            button = new JButton();
            button.setOpaque(true);

            ImageIcon icon = new ImageIcon(getClass().getResource("/detalhes-icon.png"));
            Image img = icon.getImage().getScaledInstance(26, 26, Image.SCALE_SMOOTH);
            icon = new ImageIcon(img);
            button.setIcon(icon);

            button.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    System.out.println("Botão clicado!");
                    
                    fundoPopup.setVisible(true);
                    fundoPopup.addMouseListener(new MouseAdapter() {});
                    isPushed = true;
                    fireEditingStopped(); // Para parar a edição e salvar a ação do botão
                }
            });
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            System.out.println("Editor ativado para a célula.");
            isPushed = false;
            return button;
        }

        @Override
        public Object getCellEditorValue() {
            if (isPushed) {
                // Aqui você pode adicionar a lógica que ocorre ao clicar no botão.
                return null;
            }
            return null;
        }

        @Override
        public boolean stopCellEditing() {
            isPushed = false;
            return super.stopCellEditing();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaBolsas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaBolsas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaBolsas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaBolsas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaConsultaBolsas telaConsultaBolsas = new TelaConsultaBolsas(aluno);
                telaConsultaBolsas.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFecharPopup;
    private javax.swing.JPanel fundoPopup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel panelPopup;
    private javax.swing.JTable tblConsulta;
    private javax.swing.JTextArea txtDescricaoBolsa;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNomeCurso;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }

}
