/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Blackmage
 */
public class TelaGerenciamentoBolsas extends javax.swing.JFrame {

    /**
     * Creates new form TelaGerenciamentoBolsas
     */
    public TelaGerenciamentoBolsas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPesquisa = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBolsas = new javax.swing.JTable();
        labelInst = new javax.swing.JLabel();
        btnShow = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        txtNomeCurso = new javax.swing.JTextField();
        txtNomeInst = new javax.swing.JTextField();
        txtNomePreco = new javax.swing.JTextField();
        txtNomeCidade = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1160, 720));
        setPreferredSize(new java.awt.Dimension(1160, 720));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(75, 109, 190));
        jPanel1.setLayout(null);

        btnPesquisa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tool_16205471.png"))); // NOI18N
        btnPesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisa);
        btnPesquisa.setBounds(320, 110, 40, 40);

        txtPesquisa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPesquisa.setForeground(java.awt.Color.gray);
        txtPesquisa.setText("Clique para pesquisar");
        txtPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesquisaFocusLost(evt);
            }
        });
        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(txtPesquisa);
        txtPesquisa.setBounds(80, 110, 230, 40);

        tblBolsas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblBolsas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOME DO CURSO", "NOME DA INSTITUIÇÃO", "PREÇO", "CIDADE"
            }
        ));
        jScrollPane1.setViewportView(tblBolsas);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 190, 1000, 340);

        labelInst.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        labelInst.setForeground(new java.awt.Color(255, 255, 255));
        labelInst.setText("Bolsas");
        labelInst.setToolTipText("");
        labelInst.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(labelInst);
        labelInst.setBounds(80, 60, 240, 40);

        btnShow.setText("Mostrar Bolsas");
        btnShow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        jPanel1.add(btnShow);
        btnShow.setBounds(720, 110, 170, 40);

        btnClear.setText("Limpar Bolsas");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);
        btnClear.setBounds(910, 110, 170, 40);

        txtID.setEditable(false);
        txtID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtID.setText("ID automático");
        jPanel1.add(txtID);
        txtID.setBounds(80, 540, 100, 40);

        txtNomeCurso.setForeground(java.awt.Color.gray);
        txtNomeCurso.setText("Digite o nome do curso...");
        txtNomeCurso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeCursoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeCursoFocusLost(evt);
            }
        });
        txtNomeCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCursoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomeCurso);
        txtNomeCurso.setBounds(190, 540, 220, 40);

        txtNomeInst.setForeground(java.awt.Color.gray);
        txtNomeInst.setText("Digite o nome da instituição...");
        txtNomeInst.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeInstFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeInstFocusLost(evt);
            }
        });
        txtNomeInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeInstActionPerformed(evt);
            }
        });
        jPanel1.add(txtNomeInst);
        txtNomeInst.setBounds(420, 540, 220, 40);

        txtNomePreco.setForeground(java.awt.Color.gray);
        txtNomePreco.setText("Digite o preço...");
        txtNomePreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomePrecoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomePrecoFocusLost(evt);
            }
        });
        jPanel1.add(txtNomePreco);
        txtNomePreco.setBounds(650, 540, 210, 40);

        txtNomeCidade.setForeground(java.awt.Color.gray);
        txtNomeCidade.setText("Digite a cidade...");
        txtNomeCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeCidadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeCidadeFocusLost(evt);
            }
        });
        jPanel1.add(txtNomeCidade);
        txtNomeCidade.setBounds(870, 540, 210, 40);

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Adicionar bolsa");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton1);
        jButton1.setBounds(480, 600, 240, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1160, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtNomeCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCursoActionPerformed

    private void txtNomeInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeInstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeInstActionPerformed

    private void txtNomeInstFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeInstFocusGained
        txtNomeInst.setText("");
    }//GEN-LAST:event_txtNomeInstFocusGained

    private void txtNomeInstFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeInstFocusLost
        txtNomeInst.setText("Digite o nome da instituição...");

    }//GEN-LAST:event_txtNomeInstFocusLost

    private void txtNomePrecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomePrecoFocusGained
        txtNomePreco.setText("");
    }//GEN-LAST:event_txtNomePrecoFocusGained

    private void txtNomePrecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomePrecoFocusLost
        txtNomePreco.setText("Digite o preço...");
    }//GEN-LAST:event_txtNomePrecoFocusLost

    private void txtNomeCidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeCidadeFocusGained
        txtNomeCidade.setText("");
    }//GEN-LAST:event_txtNomeCidadeFocusGained

    private void txtNomeCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeCidadeFocusLost
        txtNomeCidade.setText("Digite a cidade...");
    }//GEN-LAST:event_txtNomeCidadeFocusLost

    private void txtNomeCursoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeCursoFocusGained
        txtNomeCurso.setText("");
    }//GEN-LAST:event_txtNomeCursoFocusGained

    private void txtNomeCursoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeCursoFocusLost
        txtNomeCurso.setText("Digite o nome do curso...");
    }//GEN-LAST:event_txtNomeCursoFocusLost

    private void txtPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaFocusGained
        txtPesquisa.setText("");
    }//GEN-LAST:event_txtPesquisaFocusGained

    private void txtPesquisaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaFocusLost
        txtPesquisa.setText("Clique para pesquisar");
    }//GEN-LAST:event_txtPesquisaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciamentoBolsas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciamentoBolsas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciamentoBolsas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciamentoBolsas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerenciamentoBolsas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelInst;
    private javax.swing.JTable tblBolsas;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNomeCidade;
    private javax.swing.JTextField txtNomeCurso;
    private javax.swing.JTextField txtNomeInst;
    private javax.swing.JTextField txtNomePreco;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
