/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Entities.Admin;

/**
 *
 * @author Blackmage
 */
public class TelaDashboard extends javax.swing.JFrame {

    private static Admin admin;
    
    /**
     * Creates new form TelaDashboard
     */
    public TelaDashboard(Admin admin) {
        initComponents();
        this.admin = admin;
    }
    
    public TelaDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnGerenciarBolsas = new javax.swing.JButton();
        btnGerenciarInst = new javax.swing.JButton();
        btnGerenciarAlunos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1160, 720));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(75, 109, 190));
        jPanel2.setLayout(null);

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(75, 109, 190));
        jButton1.setText("Sign Out");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(40, 580, 250, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatar-icon.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(60, 40, 210, 250);

        btnGerenciarBolsas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnGerenciarBolsas.setForeground(java.awt.Color.white);
        btnGerenciarBolsas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bolsa-escolar.png"))); // NOI18N
        btnGerenciarBolsas.setText("Gerenciar Bolsas");
        btnGerenciarBolsas.setContentAreaFilled(false);
        btnGerenciarBolsas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGerenciarBolsas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarBolsasActionPerformed(evt);
            }
        });
        jPanel2.add(btnGerenciarBolsas);
        btnGerenciarBolsas.setBounds(10, 400, 270, 50);

        btnGerenciarInst.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnGerenciarInst.setForeground(java.awt.Color.white);
        btnGerenciarInst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/avatares-icon.png"))); // NOI18N
        btnGerenciarInst.setText("Gerenciar Instituições");
        btnGerenciarInst.setContentAreaFilled(false);
        btnGerenciarInst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGerenciarInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarInstActionPerformed(evt);
            }
        });
        jPanel2.add(btnGerenciarInst);
        btnGerenciarInst.setBounds(30, 300, 270, 60);

        btnGerenciarAlunos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnGerenciarAlunos.setForeground(java.awt.Color.white);
        btnGerenciarAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alunos-icon.png"))); // NOI18N
        btnGerenciarAlunos.setText("Gerenciar Alunos");
        btnGerenciarAlunos.setContentAreaFilled(false);
        btnGerenciarAlunos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGerenciarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarAlunosActionPerformed(evt);
            }
        });
        jPanel2.add(btnGerenciarAlunos);
        btnGerenciarAlunos.setBounds(10, 350, 270, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 330, 720);

        jLabel1.setBackground(new java.awt.Color(75, 109, 190));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DASHBOARD");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(330, 0, 830, 80);

        jTextField1.setEditable(false);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(390, 250, 210, 60);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Quantidade de alunos cadastrados");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(390, 220, 210, 30);

        jTextField2.setEditable(false);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(630, 250, 210, 60);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Quantidade de instituições cadastradas");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(620, 220, 230, 30);

        jTextField3.setEditable(false);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(870, 250, 220, 60);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Quantidade de bolsas cadastradas");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(870, 220, 220, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1160, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaLogin telaLogin = new TelaLogin();
        telaLogin.pack();
        dispose();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGerenciarBolsasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarBolsasActionPerformed
        TelaGerenciamentoBolsasAdmin telaGerenciamentoBolsasAdmin = new TelaGerenciamentoBolsasAdmin();
        this.dispose();
        telaGerenciamentoBolsasAdmin.setVisible(true);
    }//GEN-LAST:event_btnGerenciarBolsasActionPerformed

    private void btnGerenciarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarAlunosActionPerformed
        TelaGerenciamentoAlunos telaGerenciamentoAlunos = new TelaGerenciamentoAlunos();
        this.dispose();
        telaGerenciamentoAlunos.setVisible(true);
    }//GEN-LAST:event_btnGerenciarAlunosActionPerformed

    private void btnGerenciarInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarInstActionPerformed
        TelaGerenciamentoInst telaGerenciamentoInst = new TelaGerenciamentoInst();
        this.dispose();
        telaGerenciamentoInst.setVisible(true);
    }//GEN-LAST:event_btnGerenciarInstActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaDashboard telaDashboard = new TelaDashboard(admin);
                telaDashboard.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerenciarAlunos;
    private javax.swing.JButton btnGerenciarBolsas;
    private javax.swing.JButton btnGerenciarInst;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
