/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import javax.swing.JPanel;

/**
 *
 * @author Blackmage
 */
public class TelaTesteVocacional extends javax.swing.JFrame {

    /**
     * Creates new form TelaTesteVocacional
     */
    public TelaTesteVocacional() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton12 = new javax.swing.JRadioButton();
        btnGroupQ1 = new javax.swing.ButtonGroup();
        btnGroupQ2 = new javax.swing.ButtonGroup();
        btnGroupQ3 = new javax.swing.ButtonGroup();
        btnGroupQ4 = new javax.swing.ButtonGroup();
        btnGroupQ5 = new javax.swing.ButtonGroup();
        btnGroupQ6 = new javax.swing.ButtonGroup();
        btnGroupQ7 = new javax.swing.ButtonGroup();
        btnGroupQ8 = new javax.swing.ButtonGroup();
        btnGroupQ9 = new javax.swing.ButtonGroup();
        btnGroupQ10 = new javax.swing.ButtonGroup();
        btnGroupQ11 = new javax.swing.ButtonGroup();
        btnGroupQ12 = new javax.swing.ButtonGroup();
        btnGroupQ13 = new javax.swing.ButtonGroup();
        btnGroupQ14 = new javax.swing.ButtonGroup();
        btnGroupQ15 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new RoundedPanel(100, Color.WHITE);
        cards = new javax.swing.JPanel();
        card1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        card1Quizz = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton24 = new javax.swing.JRadioButton();
        btnProximo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        card2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        card2Quizz = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton37 = new javax.swing.JRadioButton();
        jRadioButton38 = new javax.swing.JRadioButton();
        jRadioButton39 = new javax.swing.JRadioButton();
        jRadioButton40 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jRadioButton41 = new javax.swing.JRadioButton();
        jRadioButton42 = new javax.swing.JRadioButton();
        jRadioButton43 = new javax.swing.JRadioButton();
        jRadioButton44 = new javax.swing.JRadioButton();
        jRadioButton45 = new javax.swing.JRadioButton();
        jRadioButton46 = new javax.swing.JRadioButton();
        jRadioButton47 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton48 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tituloTeste = new javax.swing.JLabel();

        card.setBackground(new java.awt.Color(255, 255, 255));
        card.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("4. Você se sente mais motivado(a) por:");

        btnGroupQ4.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton1.setText("a) Criar algo visualmente interessante ou único.");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        btnGroupQ4.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton2.setText("b) Resolver problemas complexos e desafios lógicos.");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        btnGroupQ4.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton3.setText("c) Ajudar as pessoas a se entenderem melhor ou resolver questões sociais.");

        btnGroupQ4.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton4.setText("d) Fazer a diferença na vida das pessoas por meio da saúde e bem-estar.");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("5. Qual dessas opções melhor descreve seus interesses acadêmicos?");

        btnGroupQ5.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton5.setText("a) Arte, design, moda ou comunicação visual.");

        btnGroupQ5.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton6.setText("b) Física, matemática, engenharia ou computação.");

        btnGroupQ5.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton7.setText("c) Psicologia, história, sociologia ou educação.");

        btnGroupQ5.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton8.setText("d) Medicina, enfermagem, fisioterapia ou biomedicina.");

        btnGroupQ6.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton9.setText("c) Lida com pessoas, auxiliando em suas questões emocionais ou sociais.");

        btnGroupQ6.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton10.setText("a) Trabalha com expressões artísticas, criando algo novo.");

        btnGroupQ6.add(jRadioButton11);
        jRadioButton11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton11.setText("b) Foca em analisar dados e resolver problemas com base em fórmulas e lógica.");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("6. Você preferiria trabalhar em uma área que:");

        btnGroupQ6.add(jRadioButton12);
        jRadioButton12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton12.setText("d) Se dedica ao cuidado físico e psicológico de outras pessoas.");

        javax.swing.GroupLayout cardLayout = new javax.swing.GroupLayout(card);
        card.setLayout(cardLayout);
        cardLayout.setHorizontalGroup(
            cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLayout.createSequentialGroup()
                .addGroup(cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2))
                    .addGroup(cardLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton8)
                            .addComponent(jRadioButton9)
                            .addComponent(jRadioButton10)
                            .addComponent(jRadioButton11)
                            .addComponent(jRadioButton12)))
                    .addGroup(cardLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3))
                    .addGroup(cardLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel4)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        cardLayout.setVerticalGroup(
            cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton8)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton12)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1160, 720));

        jPanel1.setBackground(new java.awt.Color(75, 109, 190));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(75, 109, 190));
        jPanel2.setPreferredSize(new java.awt.Dimension(650, 400));
        jPanel2.setLayout(null);

        cards.setBackground(new java.awt.Color(255, 255, 255));
        cards.setMinimumSize(new java.awt.Dimension(649, 300));
        cards.setPreferredSize(new java.awt.Dimension(650, 300));
        cards.setLayout(new java.awt.CardLayout());

        card1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        card1Quizz.setBackground(new java.awt.Color(255, 255, 255));
        card1Quizz.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("1. Em um grupo, qual papel você normalmente assume?");

        btnGroupQ1.add(jRadioButton13);
        jRadioButton13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton13.setText("a) O criativo, trazendo novas ideias e soluções inovadoras.");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });

        btnGroupQ1.add(jRadioButton14);
        jRadioButton14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton14.setText("b) O analítico, que organiza e resolve questões técnicas ou lógicas.");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });

        btnGroupQ1.add(jRadioButton15);
        jRadioButton15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton15.setText("c) O comunicativo, conectando pessoas e ajudando a mediar soluções.");

        btnGroupQ1.add(jRadioButton16);
        jRadioButton16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton16.setText("d) O cuidador, garantindo que todos se sintam bem e tenham suas necessidades atendidas.");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("2. Como você se sente em relação a trabalhar em equipe?");

        btnGroupQ2.add(jRadioButton17);
        jRadioButton17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton17.setText("a) Gosto de trabalhar em ambientes criativos, onde as ideias fluem livremente.");

        btnGroupQ2.add(jRadioButton18);
        jRadioButton18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton18.setText("b) Prefiro trabalhar em equipes onde há lógica e organização para resolver problemas.");

        btnGroupQ2.add(jRadioButton19);
        jRadioButton19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton19.setText("c) Adoro colaborar e ajudar a entender as necessidades dos outros.");

        btnGroupQ2.add(jRadioButton20);
        jRadioButton20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton20.setText("d) Me sinto bem em equipes focadas em saúde e apoio a outras pessoas.");

        btnGroupQ3.add(jRadioButton21);
        jRadioButton21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton21.setText("c) Ler sobre comportamento humano, discutir filosofia ou ajudar outras pessoas.");

        btnGroupQ3.add(jRadioButton22);
        jRadioButton22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton22.setText("a) Pintar, desenhar, criar músicas ou qualquer forma de expressão artística.");

        btnGroupQ3.add(jRadioButton23);
        jRadioButton23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton23.setText("b) Resolver enigmas, programar ou estudar ciências e matemática.");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("3. Que tipo de atividade você escolheria em seu tempo livre?");

        btnGroupQ3.add(jRadioButton24);
        jRadioButton24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton24.setText("d) Voluntariar-se em hospitais, clínicas ou em projetos sociais de saúde.");

        btnProximo.setText("Próximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout card1QuizzLayout = new javax.swing.GroupLayout(card1Quizz);
        card1Quizz.setLayout(card1QuizzLayout);
        card1QuizzLayout.setHorizontalGroup(
            card1QuizzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card1QuizzLayout.createSequentialGroup()
                .addGroup(card1QuizzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(card1QuizzLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel5))
                    .addGroup(card1QuizzLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel6))
                    .addGroup(card1QuizzLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(card1QuizzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton14)
                            .addComponent(jRadioButton13)
                            .addComponent(jRadioButton15)
                            .addComponent(jRadioButton16)
                            .addComponent(jRadioButton17)
                            .addComponent(jRadioButton18)
                            .addComponent(jRadioButton19)
                            .addComponent(jRadioButton20)
                            .addComponent(jRadioButton21)
                            .addComponent(jRadioButton22)
                            .addComponent(jRadioButton23)
                            .addComponent(jRadioButton24)))
                    .addGroup(card1QuizzLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(card1QuizzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(card1QuizzLayout.createSequentialGroup()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        card1QuizzLayout.setVerticalGroup(
            card1QuizzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card1QuizzLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton16)
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton20)
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(card1QuizzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane1.setViewportView(card1Quizz);

        javax.swing.GroupLayout card1Layout = new javax.swing.GroupLayout(card1);
        card1.setLayout(card1Layout);
        card1Layout.setHorizontalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        card1Layout.setVerticalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        cards.add(card1, "card2");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        card2Quizz.setBackground(new java.awt.Color(255, 255, 255));
        card2Quizz.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("4. Você se sente mais motivado por:");

        btnGroupQ4.add(jRadioButton37);
        jRadioButton37.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton37.setText("a) Criar algo visualmente interessante ou único.");
        jRadioButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton37ActionPerformed(evt);
            }
        });

        btnGroupQ4.add(jRadioButton38);
        jRadioButton38.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton38.setText("b) Resolver problemas complexos e desafios lógicos.");
        jRadioButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton38ActionPerformed(evt);
            }
        });

        btnGroupQ4.add(jRadioButton39);
        jRadioButton39.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton39.setText("c) Ajudar as pessoas a se entenderem melhor ou resolver questões sociais.");

        btnGroupQ4.add(jRadioButton40);
        jRadioButton40.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton40.setText("d) Fazer a diferença na vida das pessoas por meio da saúde e bem-estar.");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("5. Qual dessas opções melhor descreve seus interesses acadêmicos?");

        btnGroupQ5.add(jRadioButton41);
        jRadioButton41.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton41.setText("a) Arte, design, moda ou comunicação visual.");

        btnGroupQ5.add(jRadioButton42);
        jRadioButton42.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton42.setText("b) Física, matemática, engenharia ou computação.");

        btnGroupQ5.add(jRadioButton43);
        jRadioButton43.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton43.setText("c) Psicologia, história, sociologia ou educação.");

        btnGroupQ5.add(jRadioButton44);
        jRadioButton44.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton44.setText("d) Medicina, enfermagem, fisioterapia ou biomedicina.");

        btnGroupQ6.add(jRadioButton45);
        jRadioButton45.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton45.setText("c) Lida com pessoas, auxiliando em suas questões emocionais ou sociais.");

        btnGroupQ6.add(jRadioButton46);
        jRadioButton46.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton46.setText("a) Trabalha com expressões artísticas, criando algo novo.");

        btnGroupQ6.add(jRadioButton47);
        jRadioButton47.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton47.setText("b) Foca em analisar dados e resolver problemas com base em fórmulas e lógica.");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("6. Você preferiria trabalhar em uma área que:");

        btnGroupQ6.add(jRadioButton48);
        jRadioButton48.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jRadioButton48.setText("d) Se dedica ao cuidado físico e psicológico de outras pessoas.");

        jButton2.setText("Próximo");

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout card2QuizzLayout = new javax.swing.GroupLayout(card2Quizz);
        card2Quizz.setLayout(card2QuizzLayout);
        card2QuizzLayout.setHorizontalGroup(
            card2QuizzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card2QuizzLayout.createSequentialGroup()
                .addGroup(card2QuizzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(card2QuizzLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel11))
                    .addGroup(card2QuizzLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel12))
                    .addGroup(card2QuizzLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(card2QuizzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton38)
                            .addComponent(jRadioButton37)
                            .addComponent(jRadioButton39)
                            .addComponent(jRadioButton40)
                            .addComponent(jRadioButton41)
                            .addComponent(jRadioButton42)
                            .addComponent(jRadioButton43)
                            .addComponent(jRadioButton44)
                            .addComponent(jRadioButton45)
                            .addComponent(jRadioButton46)
                            .addComponent(jRadioButton47)
                            .addComponent(jRadioButton48)))
                    .addGroup(card2QuizzLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(card2QuizzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(card2QuizzLayout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        card2QuizzLayout.setVerticalGroup(
            card2QuizzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card2QuizzLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton40)
                .addGap(27, 27, 27)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton44)
                .addGap(27, 27, 27)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(card2QuizzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane2.setViewportView(card2Quizz);

        javax.swing.GroupLayout card2Layout = new javax.swing.GroupLayout(card2);
        card2.setLayout(card2Layout);
        card2Layout.setHorizontalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        card2Layout.setVerticalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        cards.add(card2, "card3");

        jPanel2.add(cards);
        cards.setBounds(0, 50, 650, 300);

        tituloTeste.setBackground(new java.awt.Color(0, 0, 0));
        tituloTeste.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        tituloTeste.setForeground(new java.awt.Color(75, 109, 190));
        tituloTeste.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloTeste.setText("Teste Vocacional");
        jPanel2.add(tituloTeste);
        tituloTeste.setBounds(220, 10, 210, 30);

        jPanel1.add(jPanel2, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jRadioButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton37ActionPerformed

    private void jRadioButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton38ActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        card1Quizz.setVisible(false);
        card2Quizz.setVisible(true);
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        card2Quizz.setVisible(false);
        card1Quizz.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTesteVocacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTesteVocacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTesteVocacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTesteVocacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTesteVocacional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup btnGroupQ1;
    private javax.swing.ButtonGroup btnGroupQ10;
    private javax.swing.ButtonGroup btnGroupQ11;
    private javax.swing.ButtonGroup btnGroupQ12;
    private javax.swing.ButtonGroup btnGroupQ13;
    private javax.swing.ButtonGroup btnGroupQ14;
    private javax.swing.ButtonGroup btnGroupQ15;
    private javax.swing.ButtonGroup btnGroupQ2;
    private javax.swing.ButtonGroup btnGroupQ3;
    private javax.swing.ButtonGroup btnGroupQ4;
    private javax.swing.ButtonGroup btnGroupQ5;
    private javax.swing.ButtonGroup btnGroupQ6;
    private javax.swing.ButtonGroup btnGroupQ7;
    private javax.swing.ButtonGroup btnGroupQ8;
    private javax.swing.ButtonGroup btnGroupQ9;
    private javax.swing.JButton btnProximo;
    private javax.swing.JPanel card;
    private javax.swing.JPanel card1;
    private javax.swing.JPanel card1Quizz;
    private javax.swing.JPanel card2;
    private javax.swing.JPanel card2Quizz;
    private javax.swing.JPanel cards;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton37;
    private javax.swing.JRadioButton jRadioButton38;
    private javax.swing.JRadioButton jRadioButton39;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton40;
    private javax.swing.JRadioButton jRadioButton41;
    private javax.swing.JRadioButton jRadioButton42;
    private javax.swing.JRadioButton jRadioButton43;
    private javax.swing.JRadioButton jRadioButton44;
    private javax.swing.JRadioButton jRadioButton45;
    private javax.swing.JRadioButton jRadioButton46;
    private javax.swing.JRadioButton jRadioButton47;
    private javax.swing.JRadioButton jRadioButton48;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel tituloTeste;
    // End of variables declaration//GEN-END:variables

    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }

}
